(function(g){var window=this;var L1=function(a){a.isActive()||a.start()},M1=function(a){var b={languageCode:a.languageCode,
languageName:a.languageName,displayName:g.lH(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.i,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},N1=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},xFa=function(a,b){var c=new g.kH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},yFa=function(){this.l=[];
this.i=[]},O1=function(a,b){return b?a.i.concat(a.l):a.i},P1=function(a,b){switch(b.kind){case "asr":zFa(b,a.l);
break;default:zFa(b,a.i)}},zFa=function(a,b){g.cb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},Q1=function(){g.E.call(this);
this.l=new yFa;this.C=[]},R1=function(a,b,c){Q1.call(this,a);
this.audioTrack=c;this.i=null;this.C=b.HH},S1=function(){this.segments=[]},AFa=function(a,b){var c=g.vb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.rb(a.segments,c,0,b),g.rb(a.segments,c+1,0,b)))},T1=function(a,b,c,d,e,f){g.E.call(this);
this.policy=a;this.player=b;this.X=c;this.I=d;this.C=e;this.L=f;this.W=this.player.T();this.B=new S1;this.l=this.u=this.i=null;this.J=new g.M(this.DE,1E3,this);this.events=new g.zN(this);g.L(this,this.J);g.L(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.mB);this.mB();this.DE()},BFa=function(a,b){var c=g.iy(g.zy(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.wt(c,d,3,100).then(function(e){a:{a.na();if(a.u){var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.XA(e);if(h){e=g.zy(a.u,a.policy,{});f=a.u;g.py(f.l,e,h);f.requestId=e.get("req_id");BFa(a,a.u);break a}f||null==a.I||(h=a.u.i[0],a.C?a.I(e.response,1E3*(h.startTime+a.player.sc())):a.I(e.responseText,1E3*(h.startTime+a.player.sc())))}a.u=null;a.l=null}});
a.u=b;AFa(a.B,a.u.i[0].ra)},U1=function(a,b){Q1.call(this,b.T());
this.i=a;this.G=b;this.u=null;this.B=!1;this.I=g.oD(this.G.T())&&!this.i.isManifestless},CFa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.IN(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.kH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},DFa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},EFa=function(a,b,c){var d=[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.IN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},V1=function(a,b,c,d,e){Q1.call(this,e||null);
this.videoId=b;this.aE=d;this.B={};this.i=null;b=c||g.Gp(a).hl||"";b=b.split("_").join("-");this.u=g.Ip(a,{hl:b})},W1=function(a){if(!FFa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(GFa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},X1=function(a,b,c,d,e,f){var h={};
g.Ra(h,b);g.Ra(h,a.params);g.Ra(h,c);var l={};g.Ra(l,b.Gc);a.params.Gc&&g.Ra(l,a.params.Gc);g.Ra(l,c.Gc);h.Gc=l;g.X.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.Re?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ca=!1;this.l=a;this.ia=this.ea=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.za=.96*f;this.i=h;this.ib=c;this.B=
this.ha("captions-text");this.Va=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.ga=d/360*16;this.type=0;this.Ca=this.ga*HFa(l);a=new g.Ut(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.mJ,this);a.subscribe("dragmove",this.lJ,this);a.subscribe("dragend",this.kJ,this);this.Ka=this.Ha=0;b="";this.i.windowOpacity&&(a=W1(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,
display:!1===this.i.isVisible?"none":"","text-align":IFa[this.i.textAlign]};this.Va&&(a["border-radius"]=b?this.Ca/8+"px":"");if(this.u=2===this.l.params.Re||3===this.l.params.Re)b=this.element,c="vertical-rl",1===this.i.jA&&(c="vertical-lr"),g.Ae&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.rg(b,"-o-writing-mode",c),g.rg(b,"-webkit-writing-mode",c),g.rg(b,"writing-mode",c),g.rg(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.l.params.Re&&(g.rg(b,"text-orientation",""),g.rg(b,"transform",
"rotate(180deg)"));g.rg(this.element,a);switch(this.i.Th){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},HFa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},JFa=function(a,b){var c={},d=b.background?b.background:a.i.Gc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Gc.backgroundOpacity;d=W1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Va&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ca/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ga*HFa(b)+"px";d=1;e=b.color||a.i.Gc.color;if(b.color||null!=b.textOpacity)e=W1(e),d=null==b.textOpacity?a.i.Gc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.hx&&(h=e=b.hx);var l=a.ga/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.gq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Gc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.di&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.NL&&(c.visibility="hidden");1===b.WD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.tD||g.bs,3===a.l.params.Re?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.zi||2===b.zi||3===b.zi||4===b.zi||5===b.zi)if(g.tD)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.zi){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},KFa=function(a){a.I=g.He("SPAN");
g.rg(a.I,{display:"block"});g.N(a.I,"caption-visual-line");a.B.appendChild(a.I)},LFa=function(a,b){var c=g.He("SPAN");
g.rg(c,{display:"inline-block","white-space":"pre-wrap"});g.rg(c,JFa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.rg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.rg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},MFa=function(a,b,c){a.ca=a.ca||!!c;
var d={};g.Ra(d,a.i.Gc);g.Ra(d,c||b.i);g.Ra(d,a.ib.Gc);(c=!a.I)&&KFa(a);for(var e=a.ea&&a.ia&&g.Tb(d,a.ia)?a.ea:LFa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(KFa(a),e=LFa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ie(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.tD||!g.xg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.xg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.Ce?g.rg(e,m,"1em"):g.rg(e,m,"0.5em")))}a.ia=d;a.ea=e;a.C.push(b)},Y1=function(a,b,c,d,e,f,h){X1.call(this,a,b,c,d,e,f,h);
this.type=1},Z1=function(a,b,c,d,e,f,h){X1.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.X=this.L=this.la=0;this.Y=NaN;this.Pa=0;this.Xa=null;this.ma=new g.M(this.LO,433,this);g.N(this.element,"ytp-caption-window-rollup");g.L(this,this.ma);g.rg(this.element,"overflow","hidden")},NFa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.jA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},OFa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.wk,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Xk)?(e=g.He("SPAN"),g.Pe(e,"\u2013".repeat(d)),g.rg(e,JFa(a,a.i.Gc)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.X=c.call(b,a.Y,a.Pa,(a.u?d.offsetHeight:d.offsetWidth)+1)},PFa=function(a,b){OFa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.la){var d=0<c&&0===a.la;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.kn(a.ma));g.rg(a.B,"transform",NFa(a,c));a.la=c}OFa(a)},$1=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.JF.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},a2=function(a,b,c,d,e){g.JF.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},QFa=function(a){var b="_"+b2++;
return new a2(0,0x8000000000000,0,b,a)},SFa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Ad){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=RFa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new $1(a,b,e,c,l,d,m)}switch(m.Ad){case 9:case 10:m.zi=1;break;case 11:m.zi=2;break;case 12:m.zi=3;break;case 13:m.zi=4;break;case 14:m.zi=5}return new $1(a,b,e,c,l.textContent||"",d,m)},RFa=function(a,b,c,d,e){var f=g.gq(),h=
f?g.He("DIV"):g.He("RUBY"),l=g.He("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.He("DIV"):g.He("RP");a.textContent=b;h.appendChild(a);b=f?g.He("DIV"):g.He("RT");b.textContent=c;h.appendChild(b);c=e.Ad;if(10===c||11===c||12===c||13===c||14===c)if(g.rg(b,"text-emphasis-style","filled circle"),g.rg(b,"text-emphasis-color","currentcolor"),g.rg(b,"webkit-text-emphasis","filled circle"),11===e.Ad||13===e.Ad)g.rg(b,"webkit-text-emphasis-position","under left"),g.rg(b,"text-emphasis-position","under left");c=!0;if(4===e.Ad||7===e.Ad||12===e.Ad||
14===e.Ad)g.rg(h,"ruby-position","over"),g.rg(h,"-webkit-ruby-position","before");else if(5===e.Ad||6===e.Ad||11===e.Ad||13===e.Ad)g.rg(h,"ruby-position","under"),g.rg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.He("DIV"):g.He("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.rg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.rg(f,"display","none"),f=f.nextElementSibling,g.rg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.rg(h.lastElementChild,"display","none"),d?(g.rg(h,"padding-top","0.6em"),g.rg(f,"top","0")):(g.rg(h,"padding-bottom","0.6em"),g.rg(f,"bottom","0")));return h},c2=function(){g.E.apply(this,arguments)},d2=function(a){c2.call(this);
this.C=a;this.B={};this.W={};this.X={};this.I="_"+b2++;this.L={};this.l=this.i=null;this.J=!0},e2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},f2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},g2=function(a,b){var c=e2(a,b);
return void 0!==c?c:null},i2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return h2.test(c),c},TFa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.X[d]:a.C);d=g2(b,"mh");null!=d&&(c.Yo=d);d=g2(b,"ju");null!=d&&(c.textAlign=d);d=g2(b,"pd");null!=d&&(c.Re=d);d=g2(b,"sd");null!=d&&(c.jA=d);d=i2(b,"wfc");null!=d&&(c.windowColor=d);d=e2(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},UFa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.W[d]);d=g2(b,"ap");null!=d&&(c.Th=d);d=e2(b,"cc");null!=d&&(c.Xk=d);d=e2(b,"ah");null!=d&&(c.Ug=d);d=e2(b,"rc");null!=d&&(c.wk=d);d=e2(b,"av");null!=d&&(c.Bi=d);return c},VFa=function(a,b,c,d){var e={};
g.Ra(e,UFa(a,b));g.Ra(e,TFa(a,b));d?g.Tb(e,a.C)?(d=a.I,e=a.C):d="_"+b2++:d=b.getAttribute("id")||"_"+b2++;a=e2(b,"t")+c;b=e2(b,"d")||0x8000000000000;if(2===e.Re||3===e.Re)c=e.wk,e.wk=e.Xk,e.Xk=c;return new a2(a,b,0,d,e)},j2=function(a){c2.call(this);
this.I=a;this.i=new Map;this.B=new Map;this.C=new Map;this.l=new Map},k2=function(a){a=g.de(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},WFa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.wk=a);b=b.ccColCount;void 0!==b&&(f.Xk=b);if(2===f.Re||3===f.Re)b=f.wk,f.wk=f.Xk,f.Xk=b;return new a2(c,d,0,e,f)},m2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new l2(this);this.C=new l2(this);this.i=[];this.clear()},YFa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Gm:a,
Tk:b,result:0};a=XFa[a];b=XFa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Tk===d;if(d)return{Gm:a,Tk:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Gm:a,Tk:b,result:2};return{Gm:a,Tk:b,result:3}},$Fa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,ZFa(a.B,b,c,d))},aGa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?$Fa(a,d.CC,d.DC,b):1===d.type&&a.l&496&&ZFa(a.C,d.CC,d.DC,b);a.i.length=0},n2=function(){this.type=0},o2=function(){this.state=this.Tk=this.Gm=0},bGa=function(){this.timestamp=this.i=0},p2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new n2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new bGa}},q2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},gGa=function(a,b){switch(a){case 0:return cGa[(b&127)-32];
case 1:return dGa[b&15];case 2:return eGa[b&31];case 3:return fGa[b&31]}return 0},r2=function(a){return a.u[a.row][a.l]},s2=function(a,b,c){2<=b&&1<a.l&&(--a.l,r2(a).i=0);
var d=r2(a);d.timestamp=a.C.time+0;d.i=gGa(b,c);32>a.l&&a.l++},hGa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},t2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},u2=function(a){a.row=0<a.i?a.i:1;
a.l=1;t2(a,0,15)},v2=function(a){this.u=a;
this.C=0;this.style=new n2;this.I=new p2(this.u);this.J=new p2(this.u);this.text=new p2(this.u);this.l=this.I;this.B=this.J;this.i=this.l},w2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(q2(d,c),u2(a.l),u2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(q2(d,c),t2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},iGa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},jGa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},l2=function(a){this.i=a;
this.C=0;this.u=new v2(this.i);this.I=new v2(this.i);this.l=new o2;this.B=this.u},ZFa=function(a,b,c,d){a.l.update();
b=YFa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Gm;c=b.Tk;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&s2(a,0,b),c&96&&s2(a,0,c),0!==b&&0!==c&&3===a.style.type&&q2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.Gm=e,b.Tk=c,b.state=2,b=e&8?a.I:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;hGa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));t2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:s2(b.i,0,32);break a;case 48:57===c?(d=b.i,r2(d).i=0,32>d.l&&d.l++):s2(b.i,1,c&15)}break;case 2:c&32&&s2(b.i,2,c&31);break;case 3:c&32&&s2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:iGa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,r2(d).i=0);break;case 36:d=b.i;b=r2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:w2(b,2,d);break;case 38:w2(b,3,d);break;case 39:w2(b,4,d);break;case 40:s2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);u2(d);jGa(b);break;case 43:jGa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:q2(a,d)}t2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;q2(a,d);hGa(a,b,b+1,a.i-1);t2(a,a.row,1)}break;case 46:t2(b.B,0,15);break;case 47:q2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,iGa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},kGa=function(){},x2=function(a,b,c){this.J=a;
this.I=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.J);this.l=[]},y2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},z2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},A2=function(a,b){c2.call(this);
this.l=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new m2;this.i.l=1<<this.track},B2=function(a){if("string"===typeof a)return!1;
a=new x2(a,8,0);return lGa(a)},lGa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==z2(a))return!1;
a.version=y2(a);if(1<a.version)return!1;y2(a);y2(a);y2(a);return!0},C2=function(){c2.call(this)},mGa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.di=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new $1(b,c,d,e.id,p.nodeValue,f||0<n,g.Ob(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Ra(r,l);mGa(a,b,c,d,e,!0,p,r,m)}}},D2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},nGa=function(a,b,c,d){d=Object.assign({Yo:0},d);
return new a2(a,b,c,"_"+b2++,d)},E2=function(a){g.E.call(this);
this.l=a;this.i=null},pGa=function(a){var b={};
if(a=N1(a))b.lang=a,oGa.test(a)&&(b.Re=1);return b},H2=function(a){g.HN.call(this,a);
var b=this;this.G=a;this.i=this.G.T();this.videoData=this.G.getVideoData();this.Va=this.G.La();this.B={Gc:{}};this.C={Gc:{}};this.Y=[];this.W={};this.ma={};this.X=!1;this.Ka=g.Yoa(this.videoData,this.G);this.Xa=!!this.videoData.captionTracks.length;this.ib=!!this.videoData.jh;this.Ha="3"===this.i.controlsType;this.u=this.J=this.L=this.la=this.Ia=null;this.za=new E2(this.i);this.l=null;this.ia=new g.zN(this);this.Ca=new g.X({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.go("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Jn(d));this.storage=c;c=a.nd();d=!(!c||!c.ks());this.Pa=!(!c||!c.ls());this.I=this.Ha&&d&&!this.Ka;this.ea=!this.I&&this.Ha&&this.Pa&&this.Ka;g.L(this,this.za);this.I?this.ga=this.ca=null:(this.ca=new g.gn(this.oH,void 0,this),g.L(this,this.ca),this.ga=new g.M(this.dQ,2E3,this),g.L(this,this.ga));g.L(this,this.ia);this.i.Z("caption_window_container_killswitch")||g.xN(this.player,this.Ca.element,4);g.L(this,this.Ca);this.I||
this.ia.N(a,"resize",this.CA);this.ia.N(a,"onPlaybackAudioChange",this.VM);this.ia.N(a,g.MF("captions"),function(e){b.yd(e)});
this.ia.N(a,g.NF("captions"),function(e){b.kf(e)});
F2(this,G2(this,"display-settings")||{})},qGa=function(a){if(1===a.i.la||1===a.videoData.Yn||"alwayson"===g.uI(a.videoData,"yt:cc"))return!0;
if(2===a.i.la){var b;g.sD(a.i)?b=(0,g.uDa)():b=G2(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().u;b=a.player.getAudioTrack().captionsInitialState;var d=g.uI(a.videoData,"yt:cc");if(void 0===I2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.uI(a.videoData,"yt:cc")},J2=function(a,b){if(a.l&&(void 0===b||!b)||
!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.l||"FORCED_ON"===c.u},I2=function(a){var b=void 0,c=g.Xq(g.Vq.getInstance(),65);
if(g.sD(a.i)&&null!=c){if(null!=(0,g.uDa)())return!1;b=!c}return b},L2=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
var c=b;c||(c=a.ib?!1:a.Xa?!1:!0);c=O1(a.u.l,c);for(var d=[a.videoData.captionsLanguagePreference,a.i.captionsLanguagePreference,g.uI(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(N1(c[f])===d[e])return c[f];return a.J&&a.J.B?a.J.B:(d=c.find(function(h){return h.isDefault}))?d:c[0]||K2(a)}return null},K2=function(a){return a.J&&a.J.l},M2=function(a){var b=K2(a);
return!!b&&a.l===b},rGa=function(a,b){for(var c=a.G.nd().je().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},O2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.X=c,a.X&&(g.sD(a.i)?(0,g.V_)(!!b):N2(a,"module-enabled",!!b)));a.l=b;J2(a)&&(a.l=K2(a));a.load()},sGa=function(a,b){a.i.Z("caption_window_container_killswitch")?g.xN(a.player,b,4):a.Ca.element.appendChild(b)},tGa=function(a,b){var c=a.Va.getVideoContentRect(!0).height;
if(!c)return null;var d=a.l?a.l.languageCode:null;!b.params.Re&&d&&oGa.test(d)&&(b.params.Re=1);d=a.Va.getPlayerSize();switch(null!=b.params.Yo?b.params.Yo:1<b.i.length?1:0){case 1:return new Y1(b,a.B,a.C,c,d.width,d.height,a.i.experiments);case 2:return new Z1(b,a.B,a.C,c,d.width,d.height,a.i.experiments);default:return new X1(b,a.B,a.C,c,d.width,d.height,a.i.experiments)}},F2=function(a,b,c){c=void 0===c?!1:c;
var d=P2.Gc;a.B={};g.Ra(a.B,P2);a.B.Gc={};g.Ra(a.B.Gc,d);a.C={Gc:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;h2.test(f);e.Gc.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;h2.test(f);e.Gc.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||P2.windowColor;h2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Gc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Gc.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.di?3:d.bold?1:d.di?2:0);f=f.Gc;switch(e){case 1:f.bold=!0;delete f.di;break;case 2:delete f.bold;f.di=!0;break;case 3:f.bold=!0;f.di=!0;break;default:delete f.bold,delete f.di}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Gc.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=P2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Gc.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Gc.fontFamily=f;a.loaded&&a.CA();c&&N2(a,"display-settings",b)},vGa=function(a,b){if(b&&!a.L){var c=QFa({Re:0,
lang:"da"});a.L=[c,new $1(c.start,c.end-c.start,0,c.id,"Underteksterne ser s\u00e5dan ud")];a.player.Jd(a.L)}else!b&&a.L&&(uGa(a,a.L),a.L=null)},uGa=function(a,b){a.player.fg(b);
g.Ab(b,function(c){g.kb(this.Y,c)},a);
L1(a.ca)},G2=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},N2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.VN.prototype.oq=g.ca(23,function(){this.aa();for(var a=g.re(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Le(a[b])});
g.tS.prototype.oq=g.ca(22,function(){this.i.oq()});
g.VN.prototype.ls=g.ca(21,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.tS.prototype.ls=g.ca(20,function(){return this.i.ls()});
g.VN.prototype.ks=g.ca(19,function(){return!!this.i.textTracks});
g.tS.prototype.ks=g.ca(18,function(){return this.i.ks()});
g.VN.prototype.fq=g.ca(17,function(a){this.aa();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.tS.prototype.fq=g.ca(16,function(a){this.i.fq(a)});
g.Cy.prototype.Qt=g.ca(1,function(){return 0});
g.dz.prototype.Qt=g.ca(0,function(a){return(a=this.Wh(a))?a.l:0});
var oGa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.u(Q1,g.E);g.k=Q1.prototype;g.k.ku=function(){};
g.k.lu=function(){};
g.k.Ck=function(){};
g.k.Go=function(){return""};
g.k.gG=function(){return!1};
g.k.da=function(){this.Ck();g.E.prototype.da.call(this)};
g.u(R1,Q1);R1.prototype.ku=function(a,b,c){var d=this;this.na();b=this.Go(a,b);this.Ck();this.i=g.Yp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
R1.prototype.lu=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())P1(this.l,c.value);a()};
R1.prototype.Go=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.gq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=N1(a));return g.Ip(c,d)};
R1.prototype.Ck=function(){this.i&&this.i.abort()};
S1.prototype.contains=function(a){a=g.vb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
S1.prototype.length=function(){return this.segments.length/2};
g.u(T1,g.E);g.k=T1.prototype;g.k.da=function(){g.E.prototype.da.call(this);this.l&&this.l.cancel()};
g.k.mB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.sc();var b=this.i;this.i=g.ab(this.X.sl(a).i);b!==this.i&&this.L&&this.L()};
g.k.reset=function(){this.B=new S1;this.l&&(this.l.cancel(),this.l=null)};
g.k.DE=function(){this.na();var a;if(a=null!=this.i)a=this.i,a=a.i.Lk(a);!a||this.l||this.i&&30<this.i.startTime-this.player.getCurrentTime()||(a=this.i,a=a.i.Qp(a),a.i[0].duration?(this.B.contains(a.i[0].ra)||BFa(this,a),this.i=g.ab(a.i)):!g.U(this.W.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.sc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.J.start()};
g.u(U1,Q1);g.k=U1.prototype;g.k.ku=function(a,b,c){var d=this;this.Ck();b=DFa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?EFa(this,b,"386"):EFa(this,b));if(b){var e=1E3*(b.index.Qt(b.index.Yh())-b.index.gf(b.index.Yh()));this.u=new T1(new g.Jx,this.G,b,function(f,h){c(f,a,h,e)},this.I||g.Tw(b.info),function(){d.u&&d.u.reset();
d.B=!0})}};
g.k.gG=function(){var a=this.B;this.B=!1;return a};
g.k.lu=function(a){var b=this.I?[new g.kH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.kH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?CFa(this,"386"):CFa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())P1(this.l,c.value);a()};
g.k.Ck=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.Go=function(){return""};
g.u(V1,Q1);V1.prototype.ku=function(a,b,c){var d=this;this.na();b=this.Go(a,b);this.Ck();this.i=g.Yp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
V1.prototype.lu=function(a){var b=this,c=this.u,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.aE&&(d.asrs=1);c=g.Ip(c,d);this.Ck();this.i=g.Yp(c,{format:"RAW",onSuccess:function(e){b.i=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");P1(b.l,new g.kH({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.B[m.languageCode]=m.languageName,b.C.push(m)}a()},
withCredentials:!0})};
V1.prototype.Go=function(a,b){var c=this.u,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=N1(a));return c=g.Ip(c,d)};
V1.prototype.Ck=function(){this.i&&this.i.abort()};
var h2=/^#(?:[0-9a-f]{3}){1,2}$/i,GFa=/#(.)(.)(.)/,FFa=/^#(?:[0-9a-f]{3}){1,2}$/i;var IFa=["left","right","center","justify"];g.u(X1,g.X);g.k=X1.prototype;g.k.mJ=function(a,b){var c=g.Hg(this.element,this.element.parentElement);this.Ha=a-c.x;this.Ka=b-c.y;g.N(this.element,"ytp-dragging")};
g.k.lJ=function(a,b){var c=g.Jg(this.element),d=a-this.Ha-.02*this.playerWidth,e=b-this.Ka-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.de(f,0,2));var h=(e+c.height/2)/this.za*3;h=Math.floor(g.de(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.de(d,0,1);c=(e+h/2*c.height)/this.za;c=100*g.de(c,0,1);this.l.params.Th=l;this.l.params.Bi=c;this.l.params.Ug=d;this.i.Th=l;this.i.Bi=c;this.i.Ug=d;this.DG()};
g.k.kJ=function(){g.rn(this.element,"ytp-dragging")};
g.k.DG=function(){this.yp(this.C)};
g.k.Db=function(){return this.type};
g.k.yp=function(a){var b=Math.min(this.AD(),this.maxWidth),c=this.zD(),d="";3===this.l.params.Re&&(d="rotate(180deg)");g.rg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Uw(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Ug+2;d=this.i.Th;switch(d){case 0:case 3:case 6:(b=this.i.Gc.fontSizeIncrement)&&0<b&&2!==this.i.Re&&3!==
this.i.Re&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Bi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.rg(this.element,
a)};
g.k.Uw=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ca||this.C.length>b)b=0,this.ca=!1,this.C=[],this.I=this.ia=this.ea=null,g.Je(this.B);for(;b<a.length;b++)MFa(this,a[b])};
g.k.AD=function(){return 0};
g.k.zD=function(){return 0};
g.k.toString=function(){return g.X.prototype.toString.call(this)};g.u(Y1,X1);Y1.prototype.Uw=function(a){var b=this.l.i;X1.prototype.Uw.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Ra(d,c.i);g.Ra(d,wGa);var e=c.i;var f=d}MFa(this,c,d)}};
var wGa={NL:!0};g.u(Z1,X1);g.k=Z1.prototype;g.k.DG=function(){this.ma.Og()};
g.k.LO=function(){g.rn(this.element,"ytp-rollup-mode");this.yp(this.Xa,!0)};
g.k.zD=function(){return this.u?this.X:this.L};
g.k.AD=function(){return this.u?this.L:this.X};
g.k.yp=function(a,b){this.Xa=a;if(this.l.params.wk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Pa=this.X;this.L=this.X=0;X1.prototype.yp.call(this,a);PFa(this,b)}X1.prototype.yp.call(this,a)};g.u($1,g.JF);$1.prototype.toString=function(){return g.JF.prototype.toString.call(this)};g.u(a2,g.JF);a2.prototype.toString=function(){return g.JF.prototype.toString.call(this)};
var b2=0;g.u(c2,g.E);c2.prototype.u=function(){return[]};
c2.prototype.reset=function(){};g.u(d2,c2);d2.prototype.reset=function(){this.L={};this.l=this.i=null;this.J=!0};
d2.prototype.u=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Ra(l,this.B[m]);m=f2(c,"b");null!=m&&
(l.bold=m);m=f2(c,"i");null!=m&&(l.di=m);m=f2(c,"u");null!=m&&(l.underline=m);m=g2(c,"et");null!=m&&(l.charEdgeStyle=m);m=g2(c,"of");null!=m&&(l.offset=m);m=i2(c,"bc");null!=m&&(l.background=m);m=i2(c,"ec");null!=m&&(l.hx=m);m=i2(c,"fc");null!=m&&(l.color=m);m=g2(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=e2(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=e2(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=e2(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=g2(c,"rb");null!=m&&10!==m&&0!==m&&(l.Ad=
10<m?m-1:m);c=g2(c,"hg");null!=c&&(l.WD=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.X[d]=TFa(this,c);break;case "wp":d=c.getAttribute("id"),this.W[d]=UFa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.i=VFa(this,d,e,!1);(d=this.L[this.i.id])&&d.end>this.i.start&&(d.end=this.i.start);this.L[this.i.id]=this.i;c.push(this.i);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.I;m=!!f2(d,
"a");n=(e2(d,"t")||0)+n;var p=e2(d,"d")||5E3;m||(!this.J&&this.l&&this.l.windowId===l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"===this.l.text&&(this.l.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.B[t]:null;var w=Array.from(d.childNodes);w.length&&(this.J=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],F=void 0;0<x&&(m=!0);var D=void 0;1===y.nodeType&&(D=y);if(D&&"s"===D.tagName){if((y=(y=D.getAttribute("p"))?this.B[y]:null)&&y.Ad&&(1===y.Ad?(y=w.slice(x,x+4),4===y.length&&
(F=SFa(n,p,l,m,r,y,this.B),x+=3)):F=SFa(n,p,l,m,r,[D],this.B)),!F){var G=D;F=n;D=p;y=l;var J=m,I=r,H=G.textContent?G.textContent:"",K=G.getAttribute("p");K=K?this.B[K]:null;G=e2(G,"t")||0;F=new $1(F+G,D-G,I,y,H,J,K)}}else F=new $1(n,p,r,l,y.textContent||"",m,t);h.push(F);this.l=F}if(0<h.length)for(h[0].windowId===this.I&&(this.i=VFa(this,d,e,!0),c.push(this.i)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.i.id,this.i.i.push(h),c.push(h)}e=c}else e=[];return e};var xGa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(j2,c2);j2.prototype.reset=function(){this.l.clear()};
j2.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.i.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.di=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.hx=k2(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=k2(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=k2(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Ad=10<l?l-1:l,h.zi=xGa.get(h.Ad));f.hgHorizGroup&&(h.WD=f.hgHorizGroup);this.i.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.Yo=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.Re=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.jA=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=k2(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Ug=f.ahHorPos),void 0!==f.apPoint&&(h.Th=f.apPoint),void 0!==f.avVerPos&&(h.Bi=f.avVerPos),void 0!==f.ccCols&&(h.Xk=f.ccCols),void 0!==f.rcRows&&(h.wk=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=WFa(this,m,e,f,h),d.push(e),this.l.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+b2++,l=WFa(this,m,e,f,h),d.push(l),this.l.set(h,l));0===f&&(f=5E3);l=this.l.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.i.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,F=null;w.pPenId&&(F=this.i.get(w.pPenId));if(2===(null!=l.params.Yo?l.params.Yo:1<l.i.length?1:0)&&n&&"\n"===x)continue;if(w=F&&1===F.Ad)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var D=r[w+1].pPenId;(D=this.i.get(D))&&D.Ad&&2===D.Ad?(D=r[w+2].pPenId,D=this.i.get(D),!D||!D.Ad||3>D.Ad?w=!1:(D=r[w+3].pPenId,w=(D=this.i.get(D))&&
D.Ad&&2===D.Ad?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;D=r[m+2].utf8;var G=this.i.get(r[m+2].pPenId);x=RFa(x,y,D,w,G);n=new $1(e,f,p,h,x,n,F);m+=3}else n=new $1(e+y,f-y,p,l.id,x,n,F||t);n&&(d.push(n),l.i.push(n))}n=!0}}}else d=[];return d};m2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
m2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var XFa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];n2.prototype.set=function(a){this.type=a};
n2.prototype.get=function(){return this.type};
o2.prototype.clear=function(){this.state=0};
o2.prototype.update=function(){this.state=2===this.state?1:0};
o2.prototype.isValid=function(){return 0!==this.state};
o2.prototype.matches=function(a,b){return this.isValid()&&a===this.Gm&&b===this.Tk};
bGa.prototype.reset=function(){this.timestamp=this.i=0};
p2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
p2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
p2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var cGa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],dGa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],eGa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],fGa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];v2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.I;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
l2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.I.reset(a,1)};kGa.prototype.B=function(){};g.u(x2,kGa);x2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+b2++;c=c/1E3-this.I;d=d/1E3-this.I;a=new a2(c,d-c,5,f,{textAlign:0,Th:0,Ug:2.5*b,Bi:5.33*a});e=new $1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.u(A2,c2);A2.prototype.u=function(a){a=new x2(a,a.byteLength,this.l);if(lGa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=z2(a)*(1E3/45):1===a.version&&(a.u=4294967296*z2(a)+z2(a)),a.C=y2(a);0<a.C;a.C--){var b=y2(a),c=y2(a),d=y2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,CC:c,DC:d,order:b.i.length}))}aGa(this.i,a);return a.l}return[]};
A2.prototype.reset=function(){this.i.clear()};g.u(C2,c2);
C2.prototype.u=function(a,b){for(var c=[],d=a.split(yGa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!zGa.test(f)){var l=Q2.exec(f);if(l&&4<=l.length){var m=D2(l[1]),n=D2(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var F=y[1];switch(y[0]){case "line":y=F.split(",");y[0].endsWith("%")&&(r=y[0],l.Bi=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
F.split(",");w=y[0];l.Ug=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Bi=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.Ug=0;break;case 1:l.Ug=100;break;default:l.Ug=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Th=0>r||8<r?7:r;f=f.substring(Q2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=nGa(m,n,5,x),n=new $1(m,n,5,h.id,l,!1,g.Ob(f)?void 0:f),c.push(h),c.push(n),h.i.push(n);else for(t=l.split(AGa),1===t.length?(l=5,x=nGa(m,n,l,x)):(r=l=6,x=Object.assign({Xk:32},x),x=new a2(m,n,r,"_"+b2++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.v_("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(F=y.createElement("span"),F.appendChild(y.createTextNode(p))):F=y.firstChild,mGa(this,r,n-(r-m),l,x,0<w,F,f,c)):r=D2(p)+h}Q2.lastIndex=0}}return c};
var zGa=/^NOTE/,yGa=/(?:\r\n|\r|\n){2,}/,Q2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),AGa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(E2,g.E);E2.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
E2.prototype.reset=function(){this.i&&this.i.reset()};
E2.prototype.da=function(){g.E.prototype.da.call(this);this.clear()};var P2={windowColor:"#080808",windowOpacity:0,textAlign:2,Th:7,Ug:50,Bi:100,Gc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(H2,g.HN);g.k=H2.prototype;g.k.da=function(){if(this.I||this.ea){var a=this.G.nd();a&&!a.na()&&a.oq()}else vGa(this,!1);g.HN.prototype.da.call(this)};
g.k.En=function(){if(this.Ha)return this.I||this.ea;var a=this.player.getAudioTrack().captionsInitialState;return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?J2(this):I2(this)||J2(this)?!0:qGa(this)};
g.k.load=function(){var a=this;g.HN.prototype.load.call(this);var b=!g.U(this.i.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();if(this.u)this.l&&(this.za.clear(),this.I?rGa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.ku(this.l,"json3",function(d,e,f,h){if(d){a.u.gG()&&(a.Y=[],a.G.Oe("captions"),L1(a.ca),a.za.reset());var l=a.za;f=f||0;h=h||0;if(l.l.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Nv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),B2(d)||(d=g.Xe(new Uint8Array(d))))}}else"string"===typeof d||B2(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Nv(m,0,1835295092))&&m.size?g.Xe(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!B2(n))throw Error("Invalid binary caption track data");l.i||(l.i=new A2(r,e));var t=l.i.u(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.i||(l.i=new C2),p=l.i.u(e,r),.01>Math.random()&&g.it(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.i||(l.i=new j2(pGa(e)));n=l.i.u(p,f);break b}catch(G){g.ht(G);n=[];break b}r=g.v_(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.i||(l.i=new d2(pGa(e),l.l));n=l.i.u(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var F=Error("Invalid caption track data");F.params=p;throw F;}t=n}var D=t}catch(G){g.ht(G),l.clear(),D=[]}else D=[];a.player.Jd(D);!a.X||a.ea||M2(a)||g.bD(a.i)||g.TC(a.i)||(g.ln(a.ga),D=QFa({Th:0,Ug:5,Bi:5,wk:2,textAlign:0,Re:0,lang:"da"}),a.la=[D],l=["Klik p\u00e5 "," for at g\u00e5 til indstillinger"],a.Ia||(t=new g.oL(g.EL()),g.L(a,t),a.Ia=t.element),
t=D.end-D.start,(e=g.lH(a.l))&&a.la.push(new $1(D.start,t,0,D.id,e)),a.la.push(new $1(D.start,t,0,D.id,l[0]),new $1(D.start,t,0,D.id,a.Ia,!0),new $1(D.start,t,0,D.id,l[1],!0)),a.player.Jd(a.la),g.kn(a.ga));!a.X||a.ea||M2(a)||(g.sD(a.i)?(0,g.V_)(!0):N2(a,"module-enabled",!0),a.J&&(a.J.C=a.l),a.player.Mn());a.X=!1}}),!b||this.I||this.ea||M2(this)||this.player.xa("captionschanged",M1(this.l))),b||(this.l&&!M2(this)?this.player.xa("captionschanged",M1(this.l)):this.player.xa("onCaptionsTrackListChanged"));
else{var c;this.Ka?c=new U1(this.videoData.i,this.player):this.Xa?c=new R1(this.i,this.videoData,this.player.getAudioTrack()):c=new V1(this.videoData.jh,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.i.captionsLanguagePreference||g.uI(this.videoData,"yt:cc_default_lang")||this.i.Uc,this.videoData.Mv,this.i);this.u=c;g.L(this,this.u);c.lu(function(){var d=a.player.getAudioTrack().captionsInitialState,e;"CAPTIONS_INITIAL_STATE_UNKNOWN"===d?I2(a)||a.X||qGa(a)?e=L2(a,a.X):J2(a)&&
(e=K2(a)):"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===d?e=L2(a,a.X):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===d&&J2(a)&&(e=K2(a));if(a.I||a.ea){var f=O1(a.u.l,!0);d=[];for(var h=0;h<f.length;h++){var l=f[h],m=g.He("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.lH(l));m.setAttribute("srclang",N1(l));m.setAttribute("id",l.toString());a.ea||m.setAttribute("src",a.u.Go(l,"vtt"));l===e&&m.setAttribute("default","1");d.push(m)}e=a.G.nd();e.fq(d);e=e.je();a.Pa&&a.ia.N(e.textTracks,"change",
a.pP)}else!a.l&&e&&O2(a,e),a.player.xa("onCaptionsTrackListChanged"),a.player.xa("onApiChange")})}};
g.k.unload=function(){this.I&&this.l?rGa(this,!1):(this.ga&&g.ln(this.ga),this.player.Oe("captions"),this.Y=[],this.u&&this.u.Ck(),this.za.clear(),this.L&&this.player.Jd(this.L),this.CA());g.HN.prototype.unload.call(this);this.player.Mn();this.player.xa("captionschanged",{})};
g.k.create=function(){this.En()&&this.load()};
g.k.pP=function(){for(var a=this.G.nd().je().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=O1(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.l:null)!==b&&O2(this,b,!0)};
g.k.WQ=function(){!this.l&&this.I||this.unload()};
g.k.yd=function(a){this.Y.push(a);L1(this.ca)};
g.k.kf=function(a){g.kb(this.Y,a);this.u instanceof U1&&this.u.I&&this.player.fg([a]);L1(this.ca)};
g.k.WP=function(a){if(a instanceof a2){var b=this.W[a.id];b&&b.l!==a&&(b.dispose(),delete this.W[a.id],b=null);b||(b=tGa(this,a))&&(this.W[a.id]=b)}else b=a.windowId,this.ma[b]||(this.ma[b]=[]),this.ma[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.Ca.element.id};
g.k.dQ=function(){uGa(this,this.la);this.la=null};
g.k.oH=function(){var a=this;this.ca.stop();g.Pb(this.ma);this.Y.sort(g.LF);var b=this.Y;if(this.L){var c=g.Me(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.Ab(b,this.WP,this);g.Cb(this.W,function(d,e){a.ma[e]?(d.element.parentNode||(d instanceof Z1||d instanceof Y1||g.Fb(a.W,function(f,h){h!==e&&f.l.params.Th===d.l.params.Th&&f.l.params.Ug===d.l.params.Ug&&f.l.params.Bi===d.l.params.Bi&&(f.dispose(),delete a.W[h]);return h===e},a),sGa(a,d.element)),d.yp(a.ma[e])):(d.dispose(),delete a.W[e])},this)};
g.k.hQ=function(){F2(this,{},!0);g.U(this.i.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.xa("captionssettingschanged")};
g.k.nL=function(){var a=P2.Gc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.di?3:a.bold?1:a.di?2:0,textOpacity:a.textOpacity,windowColor:P2.windowColor,windowOpacity:P2.windowOpacity};var b=G2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.vH=function(a,b){var c={};g.Ra(c,G2(this,"display-settings"));g.Ra(c,a);F2(this,c,b);this.player.xa("captionssettingschanged")};
g.k.CA=function(){!this.I&&this.loaded&&(g.Cb(this.W,function(a,b){a.dispose();delete this.W[b]},this),this.oH())};
g.k.Ge=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.de(b,-2,4);this.vH({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&O2(this,this.l,!0);break;case "stickyLoading":void 0!==b&&this.i.u&&(g.sD(this.i)?(0,g.V_)(!!b):N2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.I)break;if(!g.Na(b))break;if(g.Ob(b)){O2(this,null,!0);break}for(var d=O1(this.u.l,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==
b.languageName||(c=b.translationLanguage?xFa(f,b.translationLanguage):f)}!c||c===this.l&&this.loaded||(d=(0,g.qoa)(),e=N1(c),d.length&&e===d[d.length-1]||(d.push(e),(0,g.vDa)(d)),O2(this,c,!0))}else return this.loaded&&this.l&&!M2(this)?M1(this.l):{};return"";case "tracklist":return this.u?g.Pc(O1(this.u.l,!(!b||!b.includeAsr)),function(h){return M1(h)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.I||void 0===b||vGa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.i.u&&a.push("stickyLoading");return a};
g.k.iy=function(){var a=this.l;return a?{cc:a.vssId}:{}};
g.k.KQ=function(){this.loaded&&this.l&&!M2(this)?(g.sD(this.i)?(0,g.V_)(!1):N2(this,"module-enabled",!1),this.unload(),J2(this,!0)&&O2(this,K2(this),!1)):O2(this,M2(this)||!this.l?L2(this,!0):this.l,!0)};
g.k.VM=function(){var a=M2(this);J2(this,a)?O2(this,this.player.getAudioTrack().l,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.En()&&(a?O2(this,L2(this),!1):this.load()))};g.NN.captions=H2;})(_yt_player);
